POC
felipecastrosales/good_app pull request #1
Opened 2022-10-16 11:43 UTC by felipecastrosales

2022-11-16 09:45 UTC, gustavomoda requested changes

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/app.dart
> +export 'commons/commons.dart';
No mesmo projeto não tem muito sentido organizar os pacotes em EXPORT.

Em todo projeto que tenho acesso com esse padrão sempre encontro import com o arquivo de export, (app.dart) e com o commons (commons/commons.dart).

Acho que isso é overhead

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/commons/commons.dart
> +export 'resources/resources.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/commons/resources/resources.dart
> +export 'app_texts.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/commons/shared/context_ext.dart
> +extension MediaQueryExt on BuildContext {
Realmente é necessário estender a classe do MediaQuery para não ter atalhos a atributos da mesma classe?

```MediaQuery.of(context).width``` para ```MediaQuery.of(context).size.width```

Pouca diferença e não vejo utilidade nisso.

Acho que isso fere o princípio de KISS (https://pt.wikipedia.org/wiki/Princ%C3%ADpio_KISS)

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/commons/shared/shared.dart
> +export 'context_ext.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/core.dart
> +export 'errors/errors.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/errors/errors.dart
> +export 'exceptions/exceptions.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/errors/exceptions/exceptions.dart
> +export 'expire_token_interceptor.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/errors/failures/failures.dart
> +export 'failure.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/logger/logger.dart
> +export 'app_logger.dart';
DITTO

2022-11-16 09:45 UTC, gustavomoda commented on lib/app/core/rest_client/dio/dio.dart
> +export 'dio_rest_client.dart';
DITTO

2022-11-16 22:26 UTC, felipecastrosales commented on lib/app/commons/shared/context_ext.dart
> +extension MediaQueryExt on BuildContext {
Na verdade não, @gustavomoda. 
A extensão é para usar dessa maneira: `context.width`.
Veja aqui para mais informações: 
- https://medium.com/suamusicatech/context-extension-4cf4512d3db0

2022-11-16 22:30 UTC, felipecastrosales commented
@gustavomoda, pelo que entendi, você pediu para a remoção dos barrel files, certo?

É uma proposta que acho interessante, facilita muito o import e é feito de forma automática com o uso da extensão no VSCode.

O que eu não acho muito legal é ver e ter que fazer vários imports em um mesmo arquivo. O barrel file é uma estrutura interessante e que vejo algumas pessoas usarem para evitar isso e facilitar. 

Se for necessária a remoção, farei. Mas pergunto para direcionar os passos, tendo em vista que montei a estrutura com base nesse conceito (tanto no projeto em si quanto nos testes).

2022-11-16 22:40 UTC, felipecastrosales commented
Além disso, você acha que faz sentido em algum momento usar barrel file... ou não usar?

2022-11-23 23:57 UTC, felipecastrosales commented
@gustavomoda, realizei a remoção dos barrel files. 
Conforme conversamos na mentoria de segunda (dia 21/11/22) essa estratégia não é muito interessante tendo em vista os requisitos e propósito do projeto.

2022-11-24 10:13 UTC, gustavomoda commented on lib/app/commons/shared/context_ext.dart
> +extension MediaQueryExt on BuildContext {
Saquei! que massa! Obrigado por ensinar essa..

2022-12-06 14:44 UTC, Alba-22 commented on lib/data/storage/local_storage.dart
> +abstract class LocalStorage {
Fiquei meio perdido em como está funcionando o seu LocalStorage

A interface LocalSecureStorage está algo muito especifico pro package que está sendo usado. A interface LocalStorage se encaixa melhor como algo genérico. Pelo que vi do código, tu usou a interface LocalStorage, mas não achei onde é instanciada a FlutterSecureStorageLocalStorageImpl, que implementa apenas a  LocalSecureStorage, mas não a LocalStorage

2022-12-06 14:44 UTC, Alba-22 commented on lib/features/login/data/datasources/login_data_source_api.dart
> +        baseUrl,
Acredito que aqui esteja faltando o restante do endpoint, a parte do /v1/auth/token

2022-12-06 14:44 UTC, Alba-22 commented on test/features/login/domain/usecases/do_login_test.dart
> +        email: email,
Acredito que o mais correto para os inputs dentro da chamada do when seja usar o any(ou anyNamed) do mocktail. A ideia do mock usando a função when é que quando a doLoginRepository.login for chamada com qualquer parâmetro, ela sempre retorne o Right(tUser).
Nisso, caberia apenas ao verify que tu colocou na linha 48 validar se a doLoginRepository.login foi chamada com os parâmetros certos

2022-12-06 23:59 UTC, felipecastrosales commented on lib/features/login/data/datasources/login_data_source_api.dart
> +        baseUrl,
Isso mesmo, @Alba-22. 
Valeu pelo comentário e observação.

2022-12-07 00:21 UTC, felipecastrosales commented on lib/data/storage/local_storage.dart
> +abstract class LocalStorage {
Fala @Alba-22, valeu pelo questionamento.
A ideia é que eu tenha de fato ambas as classes, pois irei utilizá-las no `AuthRefreshTokenInterceptor` com as manipulações que farei lá - em desenvolvimento na branch `app`. 

E ideia por de trás do `FlutterSecureStorageLocalStorageImpl` é fazer algo desse estilo: 

```dart
Bind.lazySingleton<LocalSecureStorage>(
  (i) => FlutterSecureStorageLocalStorageImpl(),
  export: true
),
```

Como está em desenvolvimento ainda, isso está sujeito à mudanças. Mas essa foi uma abstração bem massa que aprendi em um projeto da Academia do Flutter (CuidaPet) - cujo somos até colegas lá.

E de fato a `LocalSecureStorage` está um pouco mais específico do que a `LocalStorage`, mas a única mudança são nos métodos `read` (de tipo genérico) e `write` (no value).

Acredito que isso terei uma noção maior e melhor em tempo de desenvolvimento.

2022-12-07 00:22 UTC, felipecastrosales commented on test/features/login/domain/usecases/do_login_test.dart
> +        email: email,
Te chamei no Discord para esclarecer um pouco a respeito do comentário. 🙏

2022-12-08 00:47 UTC, felipecastrosales commented on test/features/login/domain/usecases/do_login_test.dart
> +        email: email,
Conforme conversamos, bastava somente fazer essa alteração no when: 
```dart
() => doLoginRepository.login(
  username: any(named: 'username'),
  password: any(named: 'password'),
),
```

Valeu!

2022-12-08 00:48 UTC, felipecastrosales commented on test/features/login/domain/usecases/do_login_test.dart
> +        email: email,
Aliás, feito no último commit com algumas pequenas alterações.
https://github.com/felipecastrosales/good_app/pull/1/commits/d47923b40c2cd693926f9bdd2ebd3fab933fa516

2023-02-26 13:59 UTC, merged